### ISSUE TITLE
Chroma plugins unable to detect games

### ISSUE THREAD

**Issue by 294762577** [diogotr7/Artemis.Plugins#9]
I was trying to apply the razer chroma effect to both my keyboard and mouse by using the chroma grabber layer. But no light comes up after the supported game is loaded. My setting as below:
![image](https://user-images.githubusercontent.com/38846508/158147535-96954d39-f186-4eba-970a-f5d12f6cec87.png)

My mouse is razer mouse, if i close Artemis and use the razer synapse instead, the mouse can pick up the lighting from game without issue.

Any help is much appreciated.

**Comment by diogotr7** [comment]
If this is still a problem, please make another issue
